[package]
name = "hotdog"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "~1.5.0"
futures = "~0.3.4"
syslog_rfc5424 = "~0.6.1"
rdkafka = { version = "~0.23.1", features = ["ssl", "sasl"]}
